server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 使用绝对路径
    url: jdbc:h2:./testdb
    username: sa
    password:

  jpa:
    # 手动添加SQLiteDialect
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

